### ISSUE TITLE
Crashing when i trying to shoot with a bow

### ISSUE THREAD

**Issue by WH3Re9Tr03** [Rahjital/VSBullseye#14]
Version 1.19.0-pre.7
Attaching crashlog
[client-crash.txt](https://github.com/TeacupAngel/VSBullseye/files/13405171/client-crash.txt)

**Comment by TeacupAngel** [comment]
Sorry, that's expected right now, Bullseye isn't compatible with 1.19 yet due to some rendering changes. There's more interest than I expected though, so I might take a look if a quick release (possibly without bow animations) is feasible.

**Comment by BoNDeXx** [comment]
> Sorry, that's expected right now, Bullseye isn't compatible with 1.19 yet due to some rendering changes. There's more interest than I expected though, so I might take a look if a quick release (possibly without bow animations) is feasible.

Please do. That would be really cool
