### ISSUE TITLE
Fixes for patches

### ISSUE THREAD

**Issue by Craluminum2413** [Rahjital/VSBullseye#3]
`patches/entities-arrow`
![image](https://user-images.githubusercontent.com/69315569/147873992-eadaa96b-5742-4d7e-9140-72b72bb44302.png)
```json
{
	"op": "move",
	"frompath": "/client/shapeByType/*",
	"path": "/hax",
	"file": "game:entities/arrow.json"
},
{
	"op": "move",
	"frompath": "/hax",
	"path": "/client/shapeByType/*",
	"file": "game:entities/arrow.json"
},
```

![image](https://user-images.githubusercontent.com/69315569/147874052-60d531dc-0b07-4563-b70c-633c8ce92887.png)
```json
  {
    "op": "move",
    "frompath": "/client/texturesByType/*",
		"path": "/hax",
    "file": "game:entities/arrow.json"
  },
  {
    "op": "move",
    "frompath": "/hax",
		"path": "/client/texturesByType/*",
    "file": "game:entities/arrow.json"
  }
```

`patches/entities-spear`
![image](https://user-images.githubusercontent.com/69315569/147874093-cf3d62be-0eca-4c7a-a3ae-6f59e63447d3.png)
```json
  {
    "op": "move",
    "frompath": "/client/shapeByType/*",
		"path": "/hax",
    "file": "game:entities/spear.json"
  },
  {
    "op": "move",
    "frompath": "/hax",
		"path": "/client/shapeByType/*",
    "file": "game:entities/spear.json"
  },
```

**Comment by Craluminum2413** [comment]
To make it clearer: Your patching way is destructive for other mods, I replaced `remove` patches with `move` ones, so instead removing `wildcard` it just moves it

**Comment by TeacupAngel** [comment]
Oh, the _move_ op works now? That's great news, I remember having crash issues with it in 1.13 or so and sharing with Tyron, but I must have missed that it got fixed. That's definitely the method I want to use, thank you for letting me know!

I'll be releasing 2.2.4 soon to incorporate this and other 1.16 related issues :)
