### ISSUE TITLE
Bullseye integration with WeaponPack Gamma broke in 2.4.0

### ISSUE THREAD

**Issue by bluelightning32** [Rahjital/VSBullseye#6]
In Bullseye 2.4.0-rc.4.zip, the Bullseye aiming system was applied to the longbows from WeaponPack Gamma. However, Bullseye 2.4.0.zip stopped applying the new aiming system to those bows; it only applies to the vanilla bows.

The WeaponPack Gamma bows still work, but they use the vanilla aiming system.

**Comment by TeacupAngel** [comment]
Thank you, an update is now out to fix this issue!
