### ISSUE TITLE
Texture asset error

### ISSUE THREAD

**Issue by PhyDoesStuff** [Rahjital/VSBullseye#7]
Game version: 1.17.6
Mod version: 2.4.1

Found a missing texture warn in client-main.txt:

```
6.10.2022 17:16:14 [Warning] Texture asset 'bullseye:textures/block/metal/ingot/lead.png' not found (defined in Entity type bullseye:bullet-lead).
```

**Comment by TeacupAngel** [comment]
Thank you for the report! Thankfully that warning is entirely benign and doesn't actually cause any texture bugs in the game. A fix will be included in the next release :)
