### ISSUE TITLE
Server Error Spam Freezes Server

### ISSUE THREAD

**Issue by RogueRaiden** [Rahjital/VSBullseye#9]
Occasionally theres this endless error that will basically freeze the server while it is spammed. Not entirely sure what causes it. Had a player die with a bow drawn and it happened. didnt happen when i tested specifically. i was fighting once and canceled my bow draw somehow and it caused the issue.

error:
[https://pastebin.com/1TCYeHM7](url)

**Comment by TeacupAngel** [comment]
Thank you for the report! [Someone also reported a similar issue with slings just a day ago](https://mods.vintagestory.at/bullseye#cmt-8265), so this might somehow be related to 1.17.11, I'll have to investigate. Either way I'll do my best to release an update to safeguard against this soon!

**Comment by RogueRaiden** [comment]
Mine happened with 1.17.9 and definitely with one of the bows

**Comment by TeacupAngel** [comment]
Oh, must have been an older issue I wasn't aware of then! Either way, the newly released 2.4.2 should fix it :)
